CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TABLES (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    sb_size NUMERIC NOT NULL,
    bb_size NUMERIC NOT NULL,
    min_buy_in INTEGER NOT NULL,
    max_buy_in INTEGER NOT NULL,
    game_type TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GAMES (
    id SERIAL PRIMARY KEY,
    table_id INTEGER REFERENCES TABLES(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS HANDS (
    id SERIAL PRIMARY KEY,
    game_id INTEGER REFERENCES GAMES(id) ON DELETE CASCADE,
    is_completed BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS HAND_ACTIONS (
    id SERIAL PRIMARY KEY,
    hand_id INTEGER REFERENCES HANDS(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
